branch-protection:
  enforce_admins: true # rules apply to admins too!
  restrictions: # restrict who can push
    teams: ["maintainers", "machine_users"]
  required_pull_request_reviews:
    dismiss_stale_reviews: true # automat dismiss old reviews
    dismissal_restrictions: # allow review dismissals
      teams:
        - maintainers
        - machine_users
    require_code_owner_reviews: true # require a code owner approval
    required_approving_review_count: 1 # number of approvals
  required_status_checks:
    strict: false # we don't want to block any PR if it's not up to date, we have the rebase merge strategy and needs-rebase plugin
  orgs:
    falcosecurity:
      # dco check is required for all PRs of any falcosecurity project
      required_status_checks:
        contexts:
          - dco
      repos:
        .github:
          branches:
            master:
              protect: true
        advocacy:
          branches:
            master:
              protect: true
        charts:
          branches:
            master:
              protect: true
            gh-pages:
              protect: true
              required_pull_request_reviews:
                require_code_owner_reviews: false
                required_approving_review_count: 0
        client-go:
          branches:
            master:
              protect: true
          required_status_checks:
            contexts:
              - "ci/circleci: test"
        client-py:
          branches:
            master:
              protect: true
        client-rs:
          branches:
            master:
              protect: true
        cloud-native-security-hub:
          branches:
            master:
              protect: true
        cloud-native-security-hub-frontend:
          branches:
            master:
              protect: true
        cloud-native-security-hub-backend:
          branches:
            master:
              protect: true
        community:
          branches:
            master:
              protect: true
        driverkit:
          branches:
            master:
              protect: true
        evolution:
          branches:
            master:
              protect: true
          required_status_checks:
            contexts:
              - "ci/circleci: test"
        event-generator:
          branches:
            master:
              protect: true
        falco:
          required_pull_request_reviews:
            required_approving_review_count: 2
          required_status_checks:
            contexts:
              - "ci/circleci: integration"
              - "ci/circleci: centos7"
          branches:
            master:
              protect: true
        falcosidekick:
          branches:
            master:
              protect: true
        falco-exporter:
          branches:
            master:
              protect: true
          required_status_checks:
            contexts:
              - "ci/circleci: test"
        falcoctl:
          branches:
            master:
              protect: true
        falco-website:
          branches:
            master:
              protect: true
          required_status_checks:
            contexts:
              - "netlify/falcosecurity/deploy-preview"
        pdig:
          branches:
            master:
              protect: true
        template-repository:
          branches:
            master:
              protect: true
        test-infra:
          branches:
            master:
              protect: true
          required_status_checks:
            contexts:
              - "ci/circleci: build/amazonlinux"
              - "ci/circleci: build/amazonlinux2"
              - "ci/circleci: build/centos"
              - "ci/circleci: build/debian"
              - "ci/circleci: build/ubuntu-aws"
              - "ci/circleci: build/ubuntu-generic"

log_level: debug

pod_namespace: test-pods

prowjob_namespace: default

tide:
  context_options:
    skip-unknown-contexts: true
    from-branch-protection: true
  merge_method:
    falcosecurity/.github: rebase
    falcosecurity/advocacy: rebase
    falcosecurity/charts: rebase
    falcosecurity/client-go: rebase
    falcosecurity/client-py: rebase
    falcosecurity/client-rs: rebase
    falcosecurity/cloud-native-security-hub: rebase
    falcosecurity/cloud-native-security-hub-frontend: rebase
    falcosecurity/cloud-native-security-hub-backend: rebase
    falcosecurity/community: rebase
    falcosecurity/driverkit: rebase
    falcosecurity/evolution: rebase
    falcosecurity/event-generator: rebase
    falcosecurity/falco: rebase
    falcosecurity/falcosidekick: rebase
    falcosecurity/falco-exporter: rebase
    falcosecurity/falcoctl: rebase
    falcosecurity/falco-website: rebase
    falcosecurity/pdig: rebase
    falcosecurity/template-repository: rebase
    falcosecurity/test-infra: rebase
  queries:
    - repos:
        - falcosecurity/.github
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase
    - repos:
        - falcosecurity/advocacy
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase
    - repos:
        - falcosecurity/charts
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - do-not-merge/release-note-label-needed
        - needs-rebase
    - repos:
        - falcosecurity/client-go
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - do-not-merge/release-note-label-needed
        - needs-rebase
    - repos:
        - falcosecurity/event-generator
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase
    - repos:
        - falcosecurity/falco
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - do-not-merge/release-note-label-needed
        - needs-rebase
    - repos:
        - falcosecurity/client-py
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - do-not-merge/release-note-label-needed
        - needs-rebase
    - repos:
        - falcosecurity/client-rs
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - do-not-merge/release-note-label-needed
        - needs-rebase
    - repos:
        - falcosecurity/cloud-native-security-hub
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - do-not-merge/release-note-label-needed
        - needs-rebase
    - repos:
        - falcosecurity/cloud-native-security-hub-frontend
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - do-not-merge/release-note-label-needed
        - needs-rebase
    - repos:
        - falcosecurity/cloud-native-security-hub-backend
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - do-not-merge/release-note-label-needed
        - needs-rebase
    - repos:
        - falcosecurity/community
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase
    - repos:
        - falcosecurity/driverkit
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase
    - repos:
        - falcosecurity/evolution
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase
    - repos:
        - falcosecurity/falco
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - do-not-merge/release-note-label-needed
        - needs-rebase
    - repos:
        - falcosecurity/falcosidekick
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - do-not-merge/release-note-label-needed
        - needs-rebase
    - repos:
        - falcosecurity/falcoctl
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - do-not-merge/release-note-label-needed
        - needs-rebase
    - repos:
        - falcosecurity/falco
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - do-not-merge/release-note-label-needed
        - needs-rebase
    - repos:
        - falcosecurity/falco-exporter
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - do-not-merge/release-note-label-needed
        - needs-rebase
    - repos:
        - falcosecurity/falco-website
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase
    - repos:
        - falcosecurity/pdig
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase
    - repos:
        - falcosecurity/test-infra
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase
    - repos:
        - falcosecurity/template-repository
      labels:
        - approved
        - lgtm
        - "dco-signoff: yes"
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase
