approve:
  - repos:
      - falcosecurity/.github
      - falcosecurity/advocacy
      - falcosecurity/client-go
      - falcosecurity/client-py
      - falcosecurity/client-rs
      - falcosecurity/cloud-native-security-hub
      - falcosecurity/cloud-native-security-hub-frontend
      - falcosecurity/cloud-native-security-hub-backend
      - falcosecurity/community
      - falcosecurity/driverkit
      - falcosecurity/event-generator
      - falcosecurity/falco
      - falcosecurity/falco-exporter
      - falcosecurity/falcoctl
      - falcosecurity/falco-website
      - falcosecurity/template-repository
      - falcosecurity/test-infra
    lgtm_acts_as_approve: true
    require_self_approval: true

blunderbuss:
  max_request_count: 2
  use_status_availability: true

config_updater:
  config_file: prow/config/configs.yaml
  plugins_file: prow/config/plugins.yaml
  maps:
    prow/config/configs.yaml:
      name: configs
    prow/config/plugins.yaml:
      name: plugins

goose:
  key_path: /etc/unsplash/honk

label:
  additional_labels:
    - kind/pr
    - kind/issue

lgtm:
  - repos:
      - falcosecurity/.github
      - falcosecurity/advocacy
      - falcosecurity/client-go
      - falcosecurity/client-py
      - falcosecurity/client-rs
      - falcosecurity/cloud-native-security-hub
      - falcosecurity/cloud-native-security-hub-frontend
      - falcosecurity/cloud-native-security-hub-backend
      - falcosecurity/community
      - falcosecurity/driverkit
      - falcosecurity/event-generator
      - falcosecurity/falco
      - falcosecurity/falco-exporter
      - falcosecurity/falcoctl
      - falcosecurity/falco-website
      - falcosecurity/template-repository
      - falcosecurity/test-infra
    review_acts_as_lgtm: true
    store_tree_hash: true

repo_milestone:
  # Default/fallback milestone maintainers
  # To obtain the team ID: curl -H "Authorization: token <token>" "https://api.github.com/orgs/falcosecurity/teams"
  "":
    maintainers_id: 3283563
    maintainers_team: maintainers
  falcosecurity/falco:
    maintainers_id: 3283563
    maintainers_team: maintainers
    maintainers_friendly_name: Falco maintainers

require_matching_label:
  - missing_label: needs-kind
    org: falcosecurity
    repo: .github
    prs: true
    regexp: ^kind/
    missing_comment: |
      There is not a label identifying the kind of this PR.
      Please specify it either using `/kind <group>` or manually from the side menu.
  - missing_label: needs-kind
    org: falcosecurity
    repo: client-go
    prs: true
    regexp: ^kind/
    missing_comment: |
      There is not a label identifying the kind of this PR.
      Please specify it either using `/kind <group>` or manually from the side menu.
  - missing_label: needs-kind
    org: falcosecurity
    repo: client-py
    prs: true
    regexp: ^kind/
    missing_comment: |
      There is not a label identifying the kind of this PR.
      Please specify it either using `/kind <group>` or manually from the side menu.
  - missing_label: needs-kind
    org: falcosecurity
    repo: client-rs
    prs: true
    regexp: ^kind/
    missing_comment: |
      There is not a label identifying the kind of this PR.
      Please specify it either using `/kind <group>` or manually from the side menu.
  - missing_label: needs-kind
    org: falcosecurity
    repo: cloud-native-security-hub
    prs: true
    regexp: ^kind/
    missing_comment: |
      There is not a label identifying the kind of this PR.
      Please specify it either using `/kind <group>` or manually from the side menu.
  - missing_label: needs-kind
    org: falcosecurity
    repo: cloud-native-security-hub-frontend
    prs: true
    regexp: ^kind/
    missing_comment: |
      There is not a label identifying the kind of this PR.
      Please specify it either using `/kind <group>` or manually from the side menu.
  - missing_label: needs-kind
    org: falcosecurity
    repo: cloud-native-security-hub-backend
    prs: true
    regexp: ^kind/
    missing_comment: |
      There is not a label identifying the kind of this PR.
      Please specify it either using `/kind <group>` or manually from the side menu.
  - missing_label: needs-kind
    org: falcosecurity
    repo: driverkit
    prs: true
    regexp: ^kind/
    missing_comment: |
      There is not a label identifying the kind of this PR.
      Please specify it either using `/kind <group>` or manually from the side menu.
  - missing_label: needs-kind
    org: falcosecurity
    repo: event-generator
    prs: true
    regexp: ^kind/
    missing_comment: |
      There is not a label identifying the kind of this PR.
      Please specify it either using `/kind <group>` or manually from the side menu.
  - missing_label: needs-kind
    org: falcosecurity
    repo: falco
    issues: true
    regexp: ^kind/
    missing_comment: |
      There is not a label identifying the kind of this issue.
      Please specify it either using `/kind <group>` or manually from the side menu.
  - missing_label: needs-kind
    org: falcosecurity
    repo: falco-exporter
    issues: true
    regexp: ^kind/
    missing_comment: |
      There is not a label identifying the kind of this issue.
      Please specify it either using `/kind <group>` or manually from the side menu.
  - missing_label: needs-kind
    org: falcosecurity
    repo: falcoctl
    issues: true
    regexp: ^kind/
    missing_comment: |
      There is not a label identifying the kind of this issue.
      Please specify it either using `/kind <group>` or manually from the side menu.
  - missing_label: needs-kind
    org: falcosecurity
    repo: falco-website
    issues: true
    regexp: ^kind/
    missing_comment: |
      There is not a label identifying the kind of this issue.
      Please specify it either using `/kind <group>` or manually from the side menu.
  - missing_label: needs-kind
    org: falcosecurity
    repo: community
    issues: true
    regexp: ^kind/
    missing_comment: |
      There is not a label identifying the kind of this proposal.
      Whether it refers to an issue or to a PR in [Falco](https://github.com/falcosecurity/falco).
      Please specify it either using `/kind <group>` or manually from the side menu.
      In case you do not know which kind this proposal is please mention the maintainers using `@team/maintainers`.

retitle:
  allow_closed_issues: true

size:
  s: 10
  m: 30
  l: 90
  xl: 270
  xxl: 520

plugins:
  falcosecurity/.github:
    - approve
    - assign
    - blunderbuss
    - branchcleaner
    - cat
    - dco
    - dog
    - goose
    - help
    - hold
    - label
    - lifecycle
    - lgtm
    - require-matching-label
    - size
    - verify-owners
    - welcome
    - wip
  falcosecurity/advocacy:
    - approve
    - assign
    - blunderbuss
    - branchcleaner
    - cat
    - dco
    - dog
    - goose
    - help
    - hold
    - label
    - lifecycle
    - lgtm
    - require-matching-label
    - size
    - verify-owners
    - welcome
    - wip
  falcosecurity/client-go:
    - approve
    - assign
    - blunderbuss
    - branchcleaner
    - cat
    - dco
    - docs-no-retest
    - dog
    - golint
    - goose
    - help
    - hold
    - label
    - lifecycle
    - lgtm
    - release-note
    - require-matching-label
    - retitle
    - size
    - verify-owners
    - welcome
    - wip
  falcosecurity/client-py:
    - approve
    - assign
    - blunderbuss
    - branchcleaner
    - cat
    - dco
    - docs-no-retest
    - dog
    - goose
    - help
    - hold
    - label
    - lifecycle
    - lgtm
    - release-note
    - require-matching-label
    - retitle
    - size
    - verify-owners
    - welcome
    - wip
  falcosecurity/client-rs:
    - approve
    - assign
    - blunderbuss
    - branchcleaner
    - cat
    - dco
    - docs-no-retest
    - dog
    - goose
    - help
    - hold
    - label
    - lifecycle
    - lgtm
    - release-note
    - require-matching-label
    - retitle
    - size
    - verify-owners
    - welcome
    - wip
  falcosecurity/cloud-native-security-hub:
    - approve
    - assign
    - blunderbuss
    - branchcleaner
    - cat
    - dco
    - help
    - hold
    - label
    - lifecycle
    - lgtm
    - release-note
    - require-matching-label
    - size
    - verify-owners
    - welcome
    - wip
  falcosecurity/cloud-native-security-hub-frontend:
    - approve
    - assign
    - blunderbuss
    - branchcleaner
    - cat
    - dco
    - help
    - hold
    - label
    - lifecycle
    - lgtm
    - release-note
    - require-matching-label
    - size
    - verify-owners
    - welcome
    - wip
  falcosecurity/cloud-native-security-hub-backend:
    - approve
    - assign
    - blunderbuss
    - branchcleaner
    - cat
    - dco
    - golint
    - help
    - hold
    - label
    - lifecycle
    - lgtm
    - release-note
    - require-matching-label
    - size
    - verify-owners
    - welcome
    - wip
  falcosecurity/community:
    - approve
    - assign
    - blunderbuss
    - branchcleaner
    - cat
    - dco
    - dog
    - goose
    - help
    - hold
    - label
    - lifecycle
    - lgtm
    - require-matching-label
    - retitle
    - size
    - verify-owners
    - welcome
    - wip
  falcosecurity/driverkit:
    - approve
    - assign
    - blunderbuss
    - branchcleaner
    - cat
    - dco
    - dog
    - golint
    - goose
    - help
    - hold
    - label
    - lifecycle
    - lgtm
    - require-matching-label
    - retitle
    - size
    - verify-owners
    - welcome
    - wip
  falcosecurity/event-generator:
    - approve
    - assign
    - blunderbuss
    - branchcleaner
    - cat
    - dco
    - dog
    - golint
    - goose
    - help
    - hold
    - label
    - lifecycle
    - lgtm
    - require-matching-label
    - retitle
    - size
    - verify-owners
    - welcome
    - wip
  falcosecurity/falco:
    - approve
    - assign
    - blunderbuss
    - branchcleaner
    - cat
    - dco
    - docs-no-retest
    - dog
    - goose
    - help
    - hold
    - label
    - lifecycle
    - lgtm
    - mergecommitblocker
    - milestone
    - release-note
    - require-matching-label
    - retitle
    - size
    - verify-owners
    - welcome
    - wip
  falcosecurity/falco-exporter:
    - approve
    - assign
    - blunderbuss
    - branchcleaner
    - cat
    - dco
    - docs-no-retest
    - dog
    - golint
    - goose
    - help
    - hold
    - label
    - lifecycle
    - lgtm
    - release-note
    - require-matching-label
    - retitle
    - size
    - verify-owners
    - welcome
    - wip
  falcosecurity/falcoctl:
    - approve
    - assign
    - blunderbuss
    - branchcleaner
    - cat
    - dco
    - docs-no-retest
    - dog
    - golint
    - goose
    - help
    - hold
    - label
    - lifecycle
    - lgtm
    - release-note
    - require-matching-label
    - retitle
    - size
    - verify-owners
    - welcome
    - wip
  falcosecurity/falco-website:
    - approve
    - assign
    - blunderbuss
    - branchcleaner
    - cat
    - dco
    - dog
    - goose
    - help
    - hold
    - label
    - lifecycle
    - lgtm
    - require-matching-label
    - retitle
    - size
    - verify-owners
    - welcome
    - wip
  falcosecurity/template-repository:
    - approve
    - assign
    - blunderbuss
    - branchcleaner
    - cat
    - dco
    - dog
    - help
    - hold
    - label
    - lifecycle
    - lgtm
    - size
    - verify-owners
    - welcome
    - wip
  falcosecurity/test-infra:
    - approve
    - assign
    - blunderbuss
    - branchcleaner
    - cat
    - config-updater
    - dco
    - docs-no-retest
    - dog
    - goose
    - help
    - hold
    - lifecycle
    - lgtm
    - retitle
    - size
    - verify-owners
    - welcome
    - wip

external_plugins:
  falcosecurity/.github:
    - name: needs-rebase
      events:
        - pull_request
  falcosecurity/advocacy:
    - name: needs-rebase
      events:
        - pull_request
  falcosecurity/client-go:
    - name: needs-rebase
      events:
        - pull_request
  falcosecurity/client-py:
    - name: needs-rebase
      events:
        - pull_request
  falcosecurity/client-rs:
    - name: needs-rebase
      events:
        - pull_request
  falcosecurity/cloud-native-security-hub:
    - name: needs-rebase
      events:
        - pull_request
  falcosecurity/cloud-native-security-hub-frontend:
    - name: needs-rebase
      events:
        - pull_request
  falcosecurity/cloud-native-security-hub-backend:
    - name: needs-rebase
      events:
        - pull_request
  falcosecurity/community:
    - name: needs-rebase
      events:
        - pull_request
  falcosecurity/driverkit:
    - name: needs-rebase
      events:
        - pull_request
  falcosecurity/event-generator:
    - name: needs-rebase
      events:
        - pull_request
  falcosecurity/falco:
    - name: needs-rebase
      events:
        - pull_request
  falcosecurity/falco-exporter:
    - name: needs-rebase
      events:
        - pull_request
  falcosecurity/falcoctl:
    - name: needs-rebase
      events:
        - pull_request
  falcosecurity/falco-website:
    - name: needs-rebase
      events:
        - pull_request
  falcosecurity/template-repository:
    - name: needs-rebase
      events:
        - pull_request
  falcosecurity/test-infra:
    - name: needs-rebase
      events:
        - pull_request
