periodics:
  - name: update-dbg
    cron: "0 10 * * 7" # Run every Sunday at 10:00
    decorate: true
    extra_refs:
    # Check out the falcosecurity/test-infra repo
    # This will be the working directory
    - org: falcosecurity
      repo: test-infra
      base_ref: master
      workdir: true
    spec:
      containers:
      # See images/update-dbg
      - image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/update-dbg
        imagePullPolicy: Always
        command:
        - /entrypoint.sh
        args:
        - /etc/github-token/oauth
        env:
        - name: GH_PROXY
          value: https://api.github.com # fixme > Can't reach http://ghproxy at the moment
        volumeMounts:
        - name: github
          mountPath: /etc/github-token
          readOnly: true
        - name: gpg-signing-key
          mountPath: /root/gpg-signing-key/
          readOnly: true
      volumes:
      - name: github
        secret:
          # Secret containing a GitHub user access token with `repo` scope for creating PRs.
          secretName: oauth-token
      - name: gpg-signing-key
        secret:
          secretName: poiana-gpg-signing-key
          defaultMode: 0400
      nodeSelector:
        Archtype: "x86"
