presubmits:
  falcosecurity/test-infra:
    - name: check-prow-config
      run_if_changed: '^(config/(config|plugins).yaml$|config/jobs/.*.yaml$)'
      branches:
        - ^master$
      decorate: true
      skip_report: false
      spec:
        containers:
          - image: gcr.io/k8s-prow/checkconfig:v20201124-51a2fc530c
            command:
              - /checkconfig
            args:
            - --config-path=config/config.yaml
            - --job-config-path=config/jobs
            - --plugin-config=config/plugins.yaml
periodics:
- name: check-prow-config-periodic
  interval: 1h
  decorate: true
  extra_refs:
  - org: falcosecurity
    repo: test-infra
    base_ref: master
  spec:
    containers:
    - image: gcr.io/k8s-prow/checkconfig:v20201124-51a2fc530c
      command:
      - /checkconfig
      args:
      - --config-path=config/config.yaml
      - --job-config-path=config/jobs
      - --plugin-config=config/plugins.yaml