presubmits:
  falcosecurity/test-infra:
    - name: check-prow-config
      branches:
        - ^master$
      decorate: true
      skip_report: false
      always_run: true
      spec:
        containers:
          - image: gcr.io/k8s-prow/checkconfig:v20210108-eac8059329
            command:
              - /checkconfig
            args:
            - --config-path=config/config.yaml
            - --job-config-path=config/jobs
            - --plugin-config=config/plugins.yaml
periodics:
- name: check-prow-config-periodic
  interval: 1h
  decorate: true
  extra_refs:
  - org: falcosecurity
    repo: test-infra
    base_ref: master
  spec:
    containers:
    - image: gcr.io/k8s-prow/checkconfig:v20210108-eac8059329
      command:
      - /checkconfig
      args:
      - --config-path=config/config.yaml
      - --job-config-path=config/jobs
      - --plugin-config=config/plugins.yaml
    nodeSelector:
      Archtype: "x86"
