postsubmits:
  falcosecurity/rules:
    - name: update-rules-index-on-registry-changed-postsubmit
      decorate: true
      skip_report: false
      agent: kubernetes
      branches:
        - ^main$
      run_if_changed: "^registry.yaml"
      spec:
        containers:
          # See images/update-rules-index
          - image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/update-rules-index:latest
            imagePullPolicy: Always
            command:
              - /on-registry-changed.sh
            args:
              - /etc/github-token/oauth
            env:
              - name: GH_PROXY
                value: https://api.github.com # fixme > Can't reach http://ghproxy at the moment
            volumeMounts:
              - name: github
                mountPath: /etc/github-token
                readOnly: true
              - name: gpg-signing-key
                mountPath: /root/gpg-signing-key/
                readOnly: true
        volumes:
          - name: github
            secret:
              # Secret containing a GitHub user access token with `repo` scope for creating PRs.
              secretName: oauth-token
          - name: gpg-signing-key
            secret:
              secretName: poiana-gpg-signing-key
              defaultMode: 0400
        nodeSelector:
          Archtype: "x86"
