# PROW_INSTANCE_SPECIFIC
# Very customized metrics endpoints
apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: prow-monitoring
stringData:
  prometheus-additional.yaml: |
    - job_name: blackbox
      metrics_path: /probe
      params:
        module: [http_2xx]
      static_configs:
        - targets:
          - https://prow.falco.org
          - https://download.falco.org
          - https://falco.org
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-prober
type: Opaque
