apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: prow
  namespace: prow-monitoring
spec:
  replicas: 1
  image: docker.io/prom/alertmanager
  listenLocal: false
  nodeSelector: {}
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager
  version: v0.15.2
  storage: # Note that this section is immutable so changes require deleting and recreating the resource.
    volumeClaimTemplate:
      metadata:
        name: prometheus
      spec:
        accessModes:
        - "ReadWriteOnce"
        storageClassName: "ebs-ssd-retain"
        resources:
          requests:
            storage: 10Gi
