
postsubmits:
  falcosecurity/test-infra:
  - name: publish-images-autobump
    decorate: true
    path_alias: github.com/falcosecurity/test-infra
    skip_report: false
    agent: kubernetes
    run_if_changed: '^images/autobump/'
    branches:
      - ^master$
    spec:
      containers:
      - command:
          - "/home/prow/go/src/github.com/falcosecurity/test-infra/images/publish.sh"
        args:
          - "/home/prow/go/src/github.com/falcosecurity/test-infra/images/autobump"
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/docker-dind
        imagePullPolicy: Always
        resources:
          requests:
            memory: 3Gi
            cpu: 1.5
            ephemeral-storage: "2Gi"
        securityContext:
          privileged: true
      nodeSelector:
        Archtype: "x86"
  - name: publish-images-build-drivers
    decorate: true
    path_alias: github.com/falcosecurity/test-infra
    skip_report: false
    agent: kubernetes
    run_if_changed: '^images/build-drivers/'
    branches:
      - ^master$
    spec:
      containers:
      - command:
          - "/home/prow/go/src/github.com/falcosecurity/test-infra/images/publish.sh"
        args:
          - "/home/prow/go/src/github.com/falcosecurity/test-infra/images/build-drivers"
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/docker-dind
        imagePullPolicy: Always
        resources:
          requests:
            memory: 3Gi
            cpu: 1.5
            ephemeral-storage: "2Gi"
        securityContext:
          privileged: true
      nodeSelector:
        Archtype: "x86"
  - name: publish-images-build-plugins
    decorate: true
    path_alias: github.com/falcosecurity/test-infra
    skip_report: false
    agent: kubernetes
    run_if_changed: '^images/build-plugins/'
    branches:
      - ^master$
    spec:
      containers:
      - command:
          - "/home/prow/go/src/github.com/falcosecurity/test-infra/images/publish.sh"
        args:
          - "/home/prow/go/src/github.com/falcosecurity/test-infra/images/build-plugins"
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/docker-dind
        imagePullPolicy: Always
        resources:
          requests:
            memory: 3Gi
            cpu: 1.5
            ephemeral-storage: "2Gi"
        securityContext:
          privileged: true
      nodeSelector:
        Archtype: "x86"
  - name: publish-images-update-rules-index
    decorate: true
    path_alias: github.com/falcosecurity/test-infra
    skip_report: false
    agent: kubernetes
    run_if_changed: '^images/update-rules-index/'
    branches:
      - ^master$
    spec:
      containers:
      - command:
          - "/home/prow/go/src/github.com/falcosecurity/test-infra/images/publish.sh"
        args:
          - "/home/prow/go/src/github.com/falcosecurity/test-infra/images/update-rules-index"
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/docker-dind
        imagePullPolicy: Always
        resources:
          requests:
            memory: 3Gi
            cpu: 1.5
            ephemeral-storage: "2Gi"
        securityContext:
          privileged: true
      nodeSelector:
        Archtype: "x86"
  - name: publish-images-golang
    decorate: true
    path_alias: github.com/falcosecurity/test-infra
    skip_report: false
    agent: kubernetes
    run_if_changed: '^images/golang/'
    branches:
      - ^master$
    spec:
      containers:
      - command:
          - "/home/prow/go/src/github.com/falcosecurity/test-infra/images/publish.sh"
        args:
          - "/home/prow/go/src/github.com/falcosecurity/test-infra/images/golang"
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/docker-dind
        imagePullPolicy: Always
        resources:
          requests:
            memory: 3Gi
            cpu: 1.5
            ephemeral-storage: "2Gi"
        securityContext:
          privileged: true
      nodeSelector:
        Archtype: "x86"
  - name: publish-images-update-jobs
    decorate: true
    path_alias: github.com/falcosecurity/test-infra
    skip_report: false
    agent: kubernetes
    run_if_changed: '^images/update-jobs/'
    branches:
      - ^master$
    spec:
      containers:
      - command:
          - "/home/prow/go/src/github.com/falcosecurity/test-infra/images/publish.sh"
        args:
          - "/home/prow/go/src/github.com/falcosecurity/test-infra/images/update-jobs"
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/docker-dind
        imagePullPolicy: Always
        resources:
          requests:
            memory: 3Gi
            cpu: 1.5
            ephemeral-storage: "2Gi"
        securityContext:
          privileged: true
      nodeSelector:
        Archtype: "x86"
  - name: publish-images-update-maintainers
    decorate: true
    path_alias: github.com/falcosecurity/test-infra
    skip_report: false
    agent: kubernetes
    run_if_changed: '^images/update-maintainers/'
    branches:
      - ^master$
    spec:
      containers:
      - command:
          - "/home/prow/go/src/github.com/falcosecurity/test-infra/images/publish.sh"
        args:
          - "/home/prow/go/src/github.com/falcosecurity/test-infra/images/update-maintainers"
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/docker-dind
        imagePullPolicy: Always
        resources:
          requests:
            memory: 3Gi
            cpu: 1.5
            ephemeral-storage: "2Gi"
        securityContext:
          privileged: true
      nodeSelector:
        Archtype: "x86"
  - name: publish-images-update-falco-k8s-manifests
    decorate: true
    path_alias: github.com/falcosecurity/test-infra
    skip_report: false
    agent: kubernetes
    run_if_changed: '^images/update-falco-k8s-manifests/'
    branches:
      - ^master$
    spec:
      containers:
      - command:
          - "/home/prow/go/src/github.com/falcosecurity/test-infra/images/publish.sh"
        args:
          - "/home/prow/go/src/github.com/falcosecurity/test-infra/images/update-falco-k8s-manifests"
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/docker-dind
        imagePullPolicy: Always
        resources:
          requests:
            memory: 3Gi
            cpu: 1.5
            ephemeral-storage: "2Gi"
        securityContext:
          privileged: true
      nodeSelector:
        Archtype: "x86"
  - name: publish-images-build-docker-dind
    decorate: true
    path_alias: github.com/falcosecurity/test-infra
    skip_report: false
    agent: kubernetes
    run_if_changed: '^images/docker-dind/'
    branches:
      - ^master$
    spec:
      containers:
      - command:
          - "/home/prow/go/src/github.com/falcosecurity/test-infra/images/publish.sh"
        args:
          - "/home/prow/go/src/github.com/falcosecurity/test-infra/images/docker-dind"
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/docker-dind
        imagePullPolicy: Always
        resources:
          requests:
            memory: 3Gi
            cpu: 1.5
            ephemeral-storage: "2Gi"
        securityContext:
          privileged: true
      nodeSelector:
        Archtype: "x86"
  - name: publish-images-update-dbg
    decorate: true
    path_alias: github.com/falcosecurity/test-infra
    skip_report: false
    agent: kubernetes
    run_if_changed: '^images/update-dbg/'
    branches:
      - ^master$
    spec:
      containers:
      - command:
          - "/home/prow/go/src/github.com/falcosecurity/test-infra/images/publish.sh"
        args:
          - "/home/prow/go/src/github.com/falcosecurity/test-infra/images/update-dbg"
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/docker-dind
        imagePullPolicy: Always
        resources:
          requests:
            memory: 3Gi
            cpu: 1.5
            ephemeral-storage: "2Gi"
        securityContext:
          privileged: true
      nodeSelector:
        Archtype: "x86"
  - name: publish-images-update-kernels
    decorate: true
    path_alias: github.com/falcosecurity/test-infra
    skip_report: false
    agent: kubernetes
    run_if_changed: '^images/update-kernels/'
    branches:
      - ^master$
    spec:
      containers:
      - command:
          - "/home/prow/go/src/github.com/falcosecurity/test-infra/images/publish.sh"
        args:
          - "/home/prow/go/src/github.com/falcosecurity/test-infra/images/update-kernels"
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/docker-dind
        imagePullPolicy: Always
        resources:
          requests:
            memory: 3Gi
            cpu: 1.5
            ephemeral-storage: "2Gi"
        securityContext:
          privileged: true
      nodeSelector:
        Archtype: "x86"           
  - name: publish-images-update-drivers-website
    decorate: true
    path_alias: github.com/falcosecurity/test-infra
    skip_report: false
    agent: kubernetes
    run_if_changed: '^images/update-drivers-website/'
    branches:
      - ^master$
    spec:
      containers:
      - command:
          - "/home/prow/go/src/github.com/falcosecurity/test-infra/images/publish.sh"
        args:
          - "/home/prow/go/src/github.com/falcosecurity/test-infra/images/update-drivers-website"
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/docker-dind
        imagePullPolicy: Always
        resources:
          requests:
            memory: 3Gi
            cpu: 1.5
            ephemeral-storage: "2Gi"
        securityContext:
          privileged: true
      nodeSelector:
        Archtype: "x86"