presubmits:
  falcosecurity/test-infra:
  - name: validate-new-drivers-ubuntu-gcp-3-presubmit
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/(.+/)?ubuntu-gcp_3.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-gcp
        - "3.*"
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: DBG_MAKE_BUILD_TARGET
          value: validate
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this is 37.5% of a node
            memory: 2Gi
      tolerations:
      - key: "Availability"
        operator: "Equal"
        value: "SingleAZ"
        effect: "NoSchedule"
      nodeSelector:
        Archtype: "x86"
        Application: "jobs"
  - name: validate-new-drivers-ubuntu-gcp-4-presubmit
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/(.+/)?ubuntu-gcp_4.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-gcp
        - "4.*"
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: DBG_MAKE_BUILD_TARGET
          value: validate
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this is 37.5% of a node
            memory: 2Gi
      tolerations:
      - key: "Availability"
        operator: "Equal"
        value: "SingleAZ"
        effect: "NoSchedule"
      nodeSelector:
        Archtype: "x86"
        Application: "jobs"
  - name: validate-new-drivers-ubuntu-gcp-5-presubmit
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/(.+/)?ubuntu-gcp_5.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-gcp
        - "5.*"
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: DBG_MAKE_BUILD_TARGET
          value: validate
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this is 37.5% of a node
            memory: 2Gi
      tolerations:
      - key: "Availability"
        operator: "Equal"
        value: "SingleAZ"
        effect: "NoSchedule"
      nodeSelector:
        Archtype: "x86"
        Application: "jobs"
  - name: validate-new-drivers-ubuntu-gcp-6-presubmit
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/(.+/)?ubuntu-gcp_6.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-gcp
        - "6.*"
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: DBG_MAKE_BUILD_TARGET
          value: validate
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this 37.5% of a node
            memory: 2Gi
      tolerations:
      - key: "Availability"
        operator: "Equal"
        value: "SingleAZ"
        effect: "NoSchedule"
      nodeSelector:
        Archtype: "x86"
        Application: "jobs"
postsubmits:
  falcosecurity/test-infra:
  - name: build-new-drivers-ubuntu-gcp-3-postsubmit
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    error_on_eviction: true
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/' #x86_64/ubuntu-gcp_3.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-gcp
        - "3.*"
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this is 37.5% of a node
            memory: 2Gi
      tolerations:
      - key: "Availability"
        operator: "Equal"
        value: "SingleAZ"
        effect: "NoSchedule"
      nodeSelector:
        Archtype: "x86"
        Application: "jobs"
  - name: build-new-drivers-ubuntu-gcp-3-postsubmit-arm
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    error_on_eviction: true
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/' #aarch64/ubuntu-gcp_3.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-gcp
        - "3.*"
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this is 37.5% of a node
            memory: 2Gi
      tolerations:
      - key: "Archtype"
        operator: "Equal"
        value: "arm"
        effect: "NoSchedule"
      - key: "Availability"
        operator: "Equal"
        value: "SingleAZ"
        effect: "NoSchedule"
      nodeSelector:
        Archtype: "arm"
        Application: "jobs"
  - name: build-new-drivers-ubuntu-gcp-4-postsubmit
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    error_on_eviction: true
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/' #x86_64/ubuntu-gcp_4.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-gcp
        - "4.*"
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this is 37.5% of a node
            memory: 2Gi
      tolerations:
      - key: "Availability"
        operator: "Equal"
        value: "SingleAZ"
        effect: "NoSchedule"
      nodeSelector:
        Archtype: "x86"
        Application: "jobs"
  - name: build-new-drivers-ubuntu-gcp-4-postsubmit-arm
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    error_on_eviction: true
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/' #aarch64/ubuntu-gcp_4.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-gcp
        - "4.*"
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this is 37.5% of a node
            memory: 2Gi
      tolerations:
      - key: "Archtype"
        operator: "Equal"
        value: "arm"
        effect: "NoSchedule"
      - key: "Availability"
        operator: "Equal"
        value: "SingleAZ"
        effect: "NoSchedule"
      nodeSelector:
        Archtype: "arm"
        Application: "jobs"
  - name: build-new-drivers-ubuntu-gcp-5-postsubmit
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    error_on_eviction: true
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/' #x86_64/ubuntu-gcp_5.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-gcp
        - "5.*"
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this is 37.5% of a node
            memory: 2Gi
      tolerations:
      - key: "Availability"
        operator: "Equal"
        value: "SingleAZ"
        effect: "NoSchedule"
      nodeSelector:
        Archtype: "x86"
        Application: "jobs"
  - name: build-new-drivers-ubuntu-gcp-5-postsubmit-arm
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    error_on_eviction: true
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/' #aarch64/ubuntu-gcp_5.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-gcp
        - "5.*"
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this is 37.5% of a node
            memory: 2Gi
      tolerations:
      - key: "Archtype"
        operator: "Equal"
        value: "arm"
        effect: "NoSchedule"
      - key: "Availability"
        operator: "Equal"
        value: "SingleAZ"
        effect: "NoSchedule"
      nodeSelector:
        Archtype: "arm"
        Application: "jobs"
  - name: build-new-drivers-ubuntu-gcp-6-postsubmit
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    error_on_eviction: true
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/' #x86_64/ubuntu-gcp_6.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-gcp
        - "6.*"
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this 37.5% of a node
            memory: 2Gi
      tolerations:
      - key: "Availability"
        operator: "Equal"
        value: "SingleAZ"
        effect: "NoSchedule"
      nodeSelector:
        Archtype: "x86"
        Application: "jobs"
  - name: build-new-drivers-ubuntu-gcp-6-postsubmit-arm
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    error_on_eviction: true
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/' #aarch64/ubuntu-gcp_6.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-gcp
        - "6.*"
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this 37.5% of a node
            memory: 2Gi
      tolerations:
      - key: "Archtype"
        operator: "Equal"
        value: "arm"
        effect: "NoSchedule"
      - key: "Availability"
        operator: "Equal"
        value: "SingleAZ"
        effect: "NoSchedule"
      nodeSelector:
        Archtype: "arm"
        Application: "jobs"
