presubmits:
  falcosecurity/test-infra:
  - name: validate-new-drivers-amazonlinux-presubmit
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/(.+/)?amazonlinux_.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - amazonlinux
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: DBG_MAKE_BUILD_TARGET
          value: validate
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this is 37.5% of a node
            memory: 2Gi
      nodeSelector:
        Archtype: "x86"
  - name: validate-new-drivers-amazonlinux2-presubmit
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/(.+/)?amazonlinux2_.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - amazonlinux2
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: DBG_MAKE_BUILD_TARGET
          value: validate
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this 50% of a node
            memory: 2Gi
      nodeSelector:
        Archtype: "x86"
  - name: validate-new-drivers-amazonlinux2022-presubmit
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/(.+/)?amazonlinux2022_.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - amazonlinux2022
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: DBG_MAKE_BUILD_TARGET
          value: validate
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this is 37.5% of a node
            memory: 2Gi
      nodeSelector:
        Archtype: "x86"      
postsubmits:
  falcosecurity/test-infra:
  - name: build-new-drivers-amazonlinux-postsubmit
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/x86_64/amazonlinux_.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - amazonlinux
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this is 37.5% of a node
            memory: 2Gi
      nodeSelector:
        Archtype: "x86"
  - name: build-new-drivers-amazonlinux-postsubmit-arm
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/aarch64/amazonlinux_.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - amazonlinux
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this is 37.5% of a node
            memory: 2Gi
      nodeSelector:
        Archtype: "arm"
  - name: build-new-drivers-amazonlinux2-postsubmit
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/x86_64/amazonlinux2_.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - amazonlinux2
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this is 37.5% of a node
            memory: 2Gi
      nodeSelector:
        Archtype: "x86"
  - name: build-new-drivers-amazonlinux2-postsubmit-arm
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/aarch64/amazonlinux2_.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - amazonlinux2
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this is 37.5% of a node
            memory: 2Gi
      nodeSelector:
        Archtype: "arm"
  - name: build-new-drivers-amazonlinux2022-postsubmit
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/x86_64/amazonlinux2022_.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - amazonlinux2022
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this is 37.5% of a node
            memory: 2Gi
      nodeSelector:
        Archtype: "x86"
  - name: build-new-drivers-amazonlinux2022-postsubmit-arm
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9.+-]{5,}/aarch64/amazonlinux2022_.+'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - amazonlinux2022
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1.0
            memory: 4Gi
          requests:
            cpu: 750m #m5large is 2vpcu and 8gb ram so this is 37.5% of a node
            memory: 2Gi
      nodeSelector:
        Archtype: "arm"      
