presubmits:
  falcosecurity/test-infra:
  - name: build-drivers-amazonlinux-presubmit
    decorate: true
    always_run: false
    skip_report: true
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit\/'
    spec:
      containers:
      - command:
        - /workspace/build-drivers.sh
        - amazonlinux
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
<<<<<<< Updated upstream
=======
        resources:
          requests:
            cpu: 1500m #m5large is 2vpcu and 8gb ram so this 75% of a node
            memory: 7Gi
>>>>>>> Stashed changes
  - name: build-drivers-amazonlinux2-presubmit
    decorate: true
    always_run: false
    skip_report: true
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit\/'
    spec:
      containers:
      - command:
        - /workspace/build-drivers.sh
        - amazonlinux2
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
<<<<<<< Updated upstream
=======
        resources:
          requests:
            cpu: 1500m #m5large is 2vpcu and 8gb ram so this 75% of a node
            memory: 7Gi
>>>>>>> Stashed changes
  - name: build-drivers-centos-presubmit
    decorate: true
    always_run: false
    skip_report: true
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit\/'
    spec:
      containers:
      - command:
        - /workspace/build-drivers.sh
        - centos
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
<<<<<<< Updated upstream
=======
        resources:
          requests:
            cpu: 1500m #m5large is 2vpcu and 8gb ram so this 75% of a node
            memory: 7Gi
>>>>>>> Stashed changes
  - name: build-drivers-debian-presubmit
    decorate: true
    always_run: false
    skip_report: true
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit\/'
    spec:
      containers:
      - command:
        - /workspace/build-drivers.sh
        - debian
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 1500m #m5large is 2vpcu and 8gb ram so this 75% of a node
            memory: 7Gi
  - name: build-drivers-ubuntu-aws-presubmit
    decorate: true
    always_run: false
    skip_report: true
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit\/'
    spec:
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-aws
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 1500m #m5large is 2vpcu and 8gb ram so this 75% of a node
            memory: 7Gi
  - name: build-drivers-ubuntu-generic-presubmit
    decorate: true
    always_run: false
    skip_report: true
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit\/'
    spec:
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-generic
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
<<<<<<< Updated upstream
=======
        resources:
          requests:
            cpu: 1500m #m5large is 2vpcu and 8gb ram so this 75% of a node
            memory: 7Gi
>>>>>>> Stashed changes
periodics:
  - name: build-drivers-amazonlinux-periodic
    decorate: true
    cron: "0 03 * * 1"  
    extra_refs:
    - org: falcosecurity
      repo: test-infra
      base_ref: master
    agent: kubernetes
    spec:
      containers:
      - command:
        - /workspace/build-drivers.sh
        - amazonlinux
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
  - name: build-drivers-amazonlinux2-periodic
    decorate: true
    cron: "0 03 * * 2"  
    extra_refs:
    - org: falcosecurity
      repo: test-infra
      base_ref: master
    agent: kubernetes
    spec:
      containers:
      - command:
        - /workspace/build-drivers.sh
        - amazonlinux2
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
  - name: build-drivers-centos-periodic
    decorate: true
    cron: "0 03 * * 3"  
    extra_refs:
    - org: falcosecurity
      repo: test-infra
      base_ref: master
    agent: kubernetes
    spec:
      containers:
      - command:
        - /workspace/build-drivers.sh
        - centos
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
  - name: build-drivers-debian-periodic
    decorate: true
    cron: "0 03 * * 4"  
    extra_refs:
    - org: falcosecurity
      repo: test-infra
      base_ref: master
    agent: kubernetes
    spec:
      containers:
      - command:
        - /workspace/build-drivers.sh
        - debian
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
  - name: build-drivers-ubuntu-aws-periodic
    decorate: true
    cron: "0 03 * * 5"  
    extra_refs:
    - org: falcosecurity
      repo: test-infra
      base_ref: master
    agent: kubernetes
    spec:
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-aws
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
  - name: build-drivers-ubuntu-generic-periodic
    decorate: true
    cron: "0 03 * * 6"  
    extra_refs:
    - org: falcosecurity
      repo: test-infra
      base_ref: master
    agent: kubernetes
    spec:
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-generic
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
