presubmits:
  falcosecurity/test-infra:
  - name: build-drivers-ubuntu-generic-3-presubmit
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9]{40,}/ubuntu-generic_.*'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-generic
        - "3.*"
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 1500m #m5large is 2vpcu and 8gb ram so this 75% of a node
            memory: 6Gi
      nodeSelector:
        Archtype: "x86"
  - name: build-drivers-ubuntu-generic-4-presubmit
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9]{40,}/ubuntu-generic_.*'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-generic
        - "4.*"
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 1500m #m5large is 2vpcu and 8gb ram so this 75% of a node
            memory: 6Gi
      nodeSelector:
        Archtype: "x86"
  - name: build-drivers-ubuntu-generic-5-presubmit
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9]{40,}/ubuntu-generic_.*'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-generic
        - "5.*"
        env:
        - name: AWS_REGION
          value: eu-west-1
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 1500m #m5large is 2vpcu and 8gb ram so this 75% of a node
            memory: 6Gi
      nodeSelector:
        Archtype: "x86"
periodics:
  - name: build-drivers-ubuntu-generic-3-periodic
    decorate: true
    cron: "0 03 * * 6"
    extra_refs:
    - org: falcosecurity
      repo: test-infra
      base_ref: master
    agent: kubernetes
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-generic
        - "3.*"
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
      nodeSelector:
        Archtype: "x86"
  - name: build-drivers-ubuntu-generic-4-periodic
    decorate: true
    cron: "0 03 * * 6"
    extra_refs:
    - org: falcosecurity
      repo: test-infra
      base_ref: master
    agent: kubernetes
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-generic
        - "4.*"
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
      nodeSelector:
        Archtype: "x86"
  - name: build-drivers-ubuntu-generic-5-periodic
    decorate: true
    cron: "0 03 * * 6"
    extra_refs:
    - org: falcosecurity
      repo: test-infra
      base_ref: master
    agent: kubernetes
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-generic
        - "5.*"
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
      nodeSelector:
        Archtype: "x86"
postsubmits:
  falcosecurity/test-infra:
  - name: build-drivers-ubuntu-generic-3-postsubmit
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9]{40,}/ubuntu-generic_.*'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-generic
        - "3.*"
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 1500m #m5large is 2vpcu and 8gb ram so this 75% of a node
            memory: 6Gi
      nodeSelector:
        Archtype: "x86"
  - name: build-drivers-ubuntu-generic-4-postsubmit
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9]{40,}/ubuntu-generic_.*'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-generic
        - "4.*"
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 1500m #m5large is 2vpcu and 8gb ram so this 75% of a node
            memory: 6Gi
      nodeSelector:
        Archtype: "x86"
  - name: build-drivers-ubuntu-generic-5-postsubmit
    decorate: true
    skip_report: false
    agent: kubernetes
    branches:
      - ^master$
    run_if_changed: '^driverkit/config/[a-z0-9]{40,}/ubuntu-generic_.*'
    spec:
      serviceAccountName: driver-kit
      containers:
      - command:
        - /workspace/build-drivers.sh
        - ubuntu-generic
        - "5.*"
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: PUBLISH_S3
          value: "true"
        image: 292999226676.dkr.ecr.eu-west-1.amazonaws.com/test-infra/build-drivers:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 1500m #m5large is 2vpcu and 8gb ram so this 75% of a node
            memory: 6Gi
      nodeSelector:
        Archtype: "x86"
